services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: ai_knowledge_postgres
    environment:
      POSTGRES_DB: ai_knowledge_base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - ai_knowledge_network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: ai_knowledge_redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_knowledge_network
    restart: unless-stopped

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_knowledge_app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/ai_knowledge_base
      - REDIS_URL=redis://redis:6379
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_PUBLIC_ENDPOINT=${S3_PUBLIC_ENDPOINT}
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - ai_knowledge_network
    restart: unless-stopped
    env_file:
      - .env

  # Telegram Bot
  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: ai_knowledge_telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_URL=http://app:3000
    depends_on:
      - app
    networks:
      - ai_knowledge_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  ai_knowledge_network:
    driver: bridge
